services:
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - back

  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start

networks:
  default:
    driver: bridge