services:
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      # Evitar conflictos entre los node_modules del host y del contenedor
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - back
    command: npm start # Asegúrate de que este comando sea correcto en tu proyecto
    networks:
      - default

  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"  # Asegúrate de que este puerto sea el adecuado para tu servidor
    volumes:
      - ./server:/app  # Sincroniza el código fuente
      - ./server/src:/app/src  # Carpeta fuente sincronizada
      - ./server/dist:/app/dist  # Carpeta de salida sincronizada
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm run dev # Parcel supervisará esta carpeta para cambios
    networks:
      - default

networks:
  default:
    driver: bridge