services:
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      # Evitar conflictos entre los node_modules del host y del contenedor
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - back
    command: npm start # Asegúrate de que este comando sea correcto en tu proyecto
    networks:
      - default

  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./server:/app
      # Igual que en el servicio 'front', evitar conflictos de node_modules
      - /app/node_modules
    command: npm run dev # Este comando debe coincidir con tu `package.json`
    networks:
      - default

networks:
  default:
    driver: bridge